/* Script de Remplissage des Succès du site */

INSERT INTO `succes` (`ID_succes`, `nom_succes`, `description_succes`, `xp_donnee`, `goal`)
VALUES (1, 'Bienvenue chez vous !', 'Créer son compte sur le site', 100, 1);

INSERT INTO `succes` (`ID_succes`, `nom_succes`, `description_succes`, `xp_donnee`, `goal`)
VALUES (2, 'Première connexion !', 'Se connecter pour la première fois', 100, 1);

INSERT INTO `succes` (`ID_succes`, `nom_succes`, `description_succes`, `xp_donnee`, `goal`)
VALUES (3, 'Premier projet créé', 'Créer son premier projet', 500, 1);

INSERT INTO `succes` (`ID_succes`, `nom_succes`, `description_succes`, `xp_donnee`, `goal`)
VALUES (4, 'Trois projets créés', 'Créer trois projets', 1000, 3);

INSERT INTO `succes` (`ID_succes`, `nom_succes`, `description_succes`, `xp_donnee`, `goal`)
VALUES (5, 'Plus on est de fous....', 'Inviter un ami dans un projet', 1000, 1);

INSERT INTO `succes` (`ID_succes`, `nom_succes`, `description_succes`, `xp_donnee`, `goal`)
VALUES (6, 'Roi du chat', 'Envoyer 50 messages dans la shoutbox', 1000, 50);
